### ISSUE TITLE
v2.1.0 release issues

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#151]
Heads up folks, there's a few issues with this release. Typical that the first time I released new features without beta tags, it has some problems :D 

- [x] `getconfig` target not being migrated properly
- [x] `.secret.local` not being created in migrate
- [x] assets glob is being quoted wierdly in the `project.json`
- [x] functions build is not copying the env vars as it should, not sure why because it passes in e2e tests, ~~possibly due to above glob~~ - due to incorrect path being set
- [x] serve executor not running as somehow I've managed to leave a `@nrwl/devkit` import in instead of `@nx/devkit`

Will try to address these in 2.1.1 patch very soon

**Comment by pikilon** [comment]
Hey Simon I am working with nx version `16.8.1` and the @nx/esbuild doesn't work because the executor can't be found

```bash
> nx run firebase-functions:build


 >  NX   Cannot find module 'esbuild'

   Require stack:
   - /home/pikilon/workspace/my_project/node_modules/@nx/esbuild/src/executors/esbuild/esbuild.impl.js
   - /home/pikilon/workspace/my_project/node_modules/nx/src/config/schema-utils.js
   - /home/pikilon/workspace/my_project/node_modules/nx/src/command-line/run/executor-utils.js
   - /home/pikilon/workspace/my_project/node_modules/nx/src/command-line/run/run.js
   - /home/pikilon/workspace/my_project/node_modules/nx/bin/run-executor.js
   Pass --verbose to see the stacktrace.
   ```

**Comment by simondotm** [comment]
@pikilon - I removed `@nx/esbuild` in [this commit](https://github.com/simondotm/nx-firebase/pull/152/commits/1a909e13c927e8d8ef8835a9192f1b79f6be3ff1) as a package dependency, maybe that will fix it? 🤔

**Comment by pikilon** [comment]
> @pikilon - I removed `@nx/esbuild` in [this commit](https://github.com/simondotm/nx-firebase/pull/152/commits/1a909e13c927e8d8ef8835a9192f1b79f6be3ff1) as a package dependency, maybe that will fix it? 🤔
> 
> v2.1.1 has been released.

I have updated but functions will not compile without the library
`npx nx deploy firebase-functions`
👇
```
>  NX   Cannot find module 'esbuild'
```

**Comment by simondotm** [comment]
@pikilon hmm, it's pretty strange this error.

what's supposed to happen is that the `@simondotm/nx-firebase:init` generator declares which Nx packages it needs (of which `@nx/esbuild` is one) and they should then be installed to `package.json` when the plugin is first run.

(the plugin package itself does not need esbuild as a dependency or peerdep)

installing `@nx/esbuild` should then run its initialiser which will also add `esbuild` as a dev dependency to `package.json`

in the e2e tests I have for the plugin (using Nx 16.6.0), this is working as expected:
![image](https://github.com/simondotm/nx-firebase/assets/7404321/5b1836c0-9446-4bb8-a438-72da4dbf96be)

I'm wondering if this is an Nx issue? Some peer dep not being set properly maybe... so you get v0.17.17 instead of 0.19.2... 🤔

**Comment by simondotm** [comment]
Ok I see the same issue in my e2e test for Nx 16.8.1
![image](https://github.com/simondotm/nx-firebase/assets/7404321/83a6d9fc-16f8-4ded-a4b2-ea92a5db13a2)

**Comment by simondotm** [comment]
I just tried updating to Nx 16.9.0 and 16.9.1 but they seem to completely break my workspace with dependency conflict errors 😞 
gonna take a bit of investigation I think

**Comment by simondotm** [comment]
I think that your fix of manually changing the esbuild dependency is going to be necessary until this is figured out
